title: KVM Test Blog
email: balamuruhans@hotmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my site! My blogs are intended to share ideas, technical details, automated tests with Avocado-VT framework to functionally verify Linux KVM migration with Libvirt and Qemu. I would like to explore, research, study, learn, collaborate, exchange ideas, review comments for the betterment of the knowledge sharing with this blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: balamuruhans 
linkedin_username: balamuruhan-s-94208196

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
